// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lz4_compress
RawVector lz4_compress(RawVector input);
RcppExport SEXP _lbm2r_lz4_compress(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(lz4_compress(input));
    return rcpp_result_gen;
END_RCPP
}
// lz4_decompress
RawVector lz4_decompress(RawVector input, int uncompressed_size);
RcppExport SEXP _lbm2r_lz4_decompress(SEXP inputSEXP, SEXP uncompressed_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< int >::type uncompressed_size(uncompressed_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(lz4_decompress(input, uncompressed_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lbm2r_lz4_compress", (DL_FUNC) &_lbm2r_lz4_compress, 1},
    {"_lbm2r_lz4_decompress", (DL_FUNC) &_lbm2r_lz4_decompress, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_lbm2r(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
