# lz4.R
# The lz4_compress() and lz4_decompress() functions are auto-generated by
# Rcpp::compileAttributes() into R/RcppExports.R.

#' @useDynLib lbm2r, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL
