# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compress a raw vector using LZ4
#'
#' @param input A \code{raw} vector to compress.
#' @return A \code{raw} vector of LZ4-compressed bytes.
#' @keywords internal
lz4_compress <- function(input) {
    .Call(`_lbm2r_lz4_compress`, input)
}

#' Decompress an LZ4-compressed raw vector
#'
#' @param input A \code{raw} vector of LZ4-compressed bytes.
#' @param uncompressed_size The expected size of the decompressed output in bytes.
#' @return A \code{raw} vector of decompressed bytes.
#' @keywords internal
lz4_decompress <- function(input, uncompressed_size) {
    .Call(`_lbm2r_lz4_decompress`, input, uncompressed_size)
}

